/**
 * reportBuilder.js — turns a target's scope + findings into a formatted
 * security assessment report. Reuses CoctusDocuments' existing export
 * primitives (downloadMessageAsMarkdown/Pdf/Docx) rather than building a
 * new export pipeline — this module's only job is producing the content.
 */
const CoctusReportBuilder = (() => {
  const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];
  const SEVERITY_COLOR_HEX = { critical: '#C0392B', high: '#E67E22', medium: '#D4A017', low: '#2E86AB', info: '#6B7280' };

  function severityCounts(findings) {
    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach(f => { if (counts[f.severity] !== undefined) counts[f.severity]++; });
    return counts;
  }

  function sortedFindings(findings) {
    return [...findings].sort((a, b) => {
      const sa = SEVERITY_ORDER.indexOf(a.severity), sb = SEVERITY_ORDER.indexOf(b.severity);
      if (sa !== sb) return sa - sb;
      return b.createdAt - a.createdAt;
    });
  }

  function fmtDate(ts) { return new Date(ts).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }); }

  /** Plain-markdown version — used for the .md export and as the PDF text source. */
  function buildReportMarkdown(target) {
    const findings = sortedFindings(target.findings);
    const counts = severityCounts(target.findings);
    const lines = [];
    lines.push(`# Security Assessment Report — ${target.name}`);
    lines.push('');
    lines.push(`_Generated by Coctus AI on ${fmtDate(Date.now())}_`);
    lines.push('');
    lines.push('## Executive Summary');
    lines.push('');
    lines.push(`This report covers ${findings.length} finding(s) identified for **${target.name}**: `
      + SEVERITY_ORDER.filter(s => counts[s]).map(s => `${counts[s]} ${s}`).join(', ') + '.');
    lines.push('');
    lines.push('## Scope');
    lines.push('');
    lines.push('**In-scope:**');
    lines.push(target.scopeIn.length ? target.scopeIn.map(s => `- ${s}`).join('\n') : '_Not specified._');
    lines.push('');
    lines.push('**Out of scope:**');
    lines.push(target.scopeOut.length ? target.scopeOut.map(s => `- ${s}`).join('\n') : '_None specified._');
    lines.push('');
    if (target.scans.length) {
      lines.push('## Methodology');
      lines.push('');
      lines.push('Testing incorporated the following data sources:');
      lines.push([...new Set(target.scans.map(s => s.tool))].map(t => `- ${t}`).join('\n'));
      lines.push('');
    }
    if (target.notes && target.notes.trim()) {
      lines.push('## Engagement Notes');
      lines.push('');
      lines.push(target.notes.trim());
      lines.push('');
    }
    lines.push('## Findings');
    lines.push('');
    if (!findings.length) {
      lines.push('_No findings logged._');
    } else {
      findings.forEach((f, i) => {
        lines.push(`### ${i + 1}. ${f.title}`);
        lines.push('');
        lines.push(`**Severity:** ${f.severity.toUpperCase()}${f.cvss ? `  |  **CVSS:** ${f.cvss}` : ''}  |  **Status:** ${f.status}`);
        lines.push('');
        if (f.description) { lines.push('**Description**'); lines.push(''); lines.push(f.description); lines.push(''); }
        if (f.poc) { lines.push('**Proof of Concept / Reproduction Steps**'); lines.push(''); lines.push(f.poc); lines.push(''); }
        lines.push(`_Logged ${fmtDate(f.createdAt)}_`);
        lines.push('');
        lines.push('---');
        lines.push('');
      });
    }
    return lines.join('\n');
  }

  /** HTML version — used for the .docx export. Inline styles since docx conversion doesn't read external CSS. */
  function buildReportHtml(target) {
    const esc = s => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const nl2br = s => esc(s).replace(/\n/g, '<br>');
    const findings = sortedFindings(target.findings);
    const counts = severityCounts(target.findings);
    const parts = [];
    parts.push(`<h1>Security Assessment Report — ${esc(target.name)}</h1>`);
    parts.push(`<p><em>Generated by Coctus AI on ${fmtDate(Date.now())}</em></p>`);
    parts.push('<h2>Executive Summary</h2>');
    parts.push(`<p>This report covers ${findings.length} finding(s) identified for <strong>${esc(target.name)}</strong>: `
      + SEVERITY_ORDER.filter(s => counts[s]).map(s => `${counts[s]} ${s}`).join(', ') + '.</p>');
    parts.push('<h2>Scope</h2>');
    parts.push('<p><strong>In-scope:</strong></p>');
    parts.push(target.scopeIn.length ? `<ul>${target.scopeIn.map(s => `<li>${esc(s)}</li>`).join('')}</ul>` : '<p><em>Not specified.</em></p>');
    parts.push('<p><strong>Out of scope:</strong></p>');
    parts.push(target.scopeOut.length ? `<ul>${target.scopeOut.map(s => `<li>${esc(s)}</li>`).join('')}</ul>` : '<p><em>None specified.</em></p>');
    if (target.scans.length) {
      parts.push('<h2>Methodology</h2>');
      parts.push('<p>Testing incorporated the following data sources:</p>');
      parts.push(`<ul>${[...new Set(target.scans.map(s => s.tool))].map(t => `<li>${esc(t)}</li>`).join('')}</ul>`);
    }
    if (target.notes && target.notes.trim()) {
      parts.push('<h2>Engagement Notes</h2>');
      parts.push(`<p>${nl2br(target.notes.trim())}</p>`);
    }
    parts.push('<h2>Findings</h2>');
    if (!findings.length) {
      parts.push('<p><em>No findings logged.</em></p>');
    } else {
      findings.forEach((f, i) => {
        const color = SEVERITY_COLOR_HEX[f.severity] || '#6B7280';
        parts.push(`<h3>${i + 1}. ${esc(f.title)}</h3>`);
        parts.push(`<p><strong style="color:${color};">${f.severity.toUpperCase()}</strong>${f.cvss ? `  |  <strong>CVSS:</strong> ${esc(f.cvss)}` : ''}  |  <strong>Status:</strong> ${esc(f.status)}</p>`);
        if (f.description) parts.push(`<p><strong>Description</strong><br>${nl2br(f.description)}</p>`);
        if (f.poc) parts.push(`<p><strong>Proof of Concept / Reproduction Steps</strong><br>${nl2br(f.poc)}</p>`);
        parts.push(`<p><em>Logged ${fmtDate(f.createdAt)}</em></p><hr>`);
      });
    }
    return parts.join('\n');
  }

  function exportMarkdown(target) {
    CoctusDocuments.downloadMessageAsMarkdown(buildReportMarkdown(target), `${target.name} — report`);
  }
  function exportPdf(target) {
    CoctusDocuments.downloadMessageAsPdf(buildReportMarkdown(target), `${target.name} — Security Report`);
  }
  function exportDocx(target) {
    CoctusDocuments.downloadMessageAsDocx(buildReportHtml(target), `${target.name} — report`);
  }

  return { buildReportMarkdown, buildReportHtml, exportMarkdown, exportPdf, exportDocx };
})();
